ByTorsten:
  Neos:
    ExtendUi:
      replacements:
        'Content/Components/ContentDimensionController': 'resource://ByTorsten.Neos.ContentDimensionSelector/Public/JavaScript/Content/Components/ContentDimensionController.js'